name: my_flutter_app
description: A Flutter project demonstrating Firebase, Google Sign-In, and AdMob integration.

publish_to: 'none'  # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pay: ^3.2.1
  cupertino_icons: ^1.0.2

  # Firebase dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  # Google Sign-In
  google_sign_in: ^6.3.0

  # AdMob (Google Mobile Ads)
  google_mobile_ads: ^5.3.1
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
